version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"

  itinerary_generator:
    build: ./itinerary_generator
    volumes:
      - ./itinerary_generator:/code
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DB_NAME}
      TOGETHER_API_KEY: ${TOGETHER_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_ITINERARY_URL: http://localhost:8001
    depends_on:
      - backend
      - itinerary_generator
    ports:
      - "3000:3000"

volumes:
  postgres_data:
