version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tripdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/tripdb
      SECRET_KEY: "tripsecret"
    depends_on:
      - db
    ports:
      - "8000:8000"

  itinerary_generator:
    build: ./itinerary_generator
    volumes:
      - ./itinerary_generator:/code
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/tripdb
      TOGETHER_API_KEY: c0cc2986a32364b755042e290267197e4ef893c9ccbe20ea2f1c380595d9f6dd
      SECRET_KEY: "tripsecret"
    depends_on:
      - db
    ports:
      - "8001:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_ITINERARY_URL: http://localhost:8001
    depends_on:
      - backend
      - itinerary_generator
    ports:
      - "3000:3000"

volumes:
  postgres_data:
